# Generated by Django 4.1.7 on 2023-03-14 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Age', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=0)),
                ('Specialization', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Age', models.IntegerField(default=0)),
                ('Promblem', models.CharField(max_length=255)),
                ('Doctor_prescription', models.TextField(max_length=1000)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.doctor')),
            ],
        ),
    ]
